baseURL = 'https://huchunfang.github.io/nothing/'
languageCode = 'en-us'
title = '巴以冲突'
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
publishDir =  "docs"

